replicaCount: 1

image:
  repository: simple-website
  tag: latest
  pullPolicy: Never # This is a workaround in local development

  # Command to load image locally:
  # minikube image load simple-website:latest

service:
  type: NodePort
  port: 3000
  nodePort: 30080
